name: PR test

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache gradle dependencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle${{ hashFiles('gradle/wrapper/gradle-wrapper.properties')}}-${{ hashFiles('gradle.properties')}}
        restore-keys: |
          ${{ runner.os }}-gradle${{ hashFiles('gradle/wrapper/gradle-wrapper.properties')}}-
          ${{ runner.os }}-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run tests with Gradle
      run: ./gradlew testDebug --no-daemon
    - name: Archive test results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test-results
        path: "yoti-sdk/build/reports/tests/"

    - name: Build sample-1
      run: ./gradlew sample-app:assembleDebug --no-daemon
    - name: Upload sample-1
      uses: actions/upload-artifact@v1
      with:
        name: sample-1
        path: "sample-app/build/outputs/apk/"

    - name: Build sample-2
      run: ./gradlew sample-app-2:assembleDebug --no-daemon
    - name: Upload sample-2
      uses: actions/upload-artifact@v1
      with:
        name: sample-2
        path: "sample-app-2/build/outputs/apk/"

    - name: Build sample-3
      run: ./gradlew sample-app-3:assembleDebug --no-daemon
    - name: Upload sample-3
      uses: actions/upload-artifact@v1
      with:
        name: sample-3
        path: "sample-app-3/build/outputs/apk/"
